name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      device:
        description: '设备型号 (如 PSG1218)'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      KERNEL: 3.4
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        apt-get update
        apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev wget

    - name: Clone source
      run: |
        git clone --depth=1 https://github.com/uwjtg/rt-n56u.git $GITHUB_WORKSPACE/rt-n56u
        cd $GITHUB_WORKSPACE/rt-n56u/toolchain-mipsel
        chmod +x dl_toolchain.sh
        ./dl_toolchain.sh

    - name: Build firmware
      env:
        TNAME: ${{ github.event.inputs.device || 'PSG1218' }}  # 默认编译K2P
      run: |
        cd $GITHUB_WORKSPACE/rt-n56u/trunk
        cp -f configs/templates/$TNAME.config .config
        
        # 清理旧配置
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config

        # 添加新配置
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y" >> .config

        ./clear_tree
        ./build_firmware_modify $TNAME 0
        mv -f images/*.trx $GITHUB_WORKSPACE/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Padavan-${{ env.TNAME }}-固件
        path: $GITHUB_WORKSPACE/*.trx
