name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        sudo chmod -R 777 /opt
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
        else
        #git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        git clone --depth=1 https://e.coding.net/hanwckf/rt-n56u/padavan.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sudo sh dl_toolchain.sh
        #sudo ./clean_toolchain
        #sudo ./build_toolchain
        sudo mkdir -p /opt/images/
        
        ######################################################################
        # 以下添加vnt项目克隆（新增部分）
        ######################################################################
        cd /opt/rt-n56u/trunk/user
        git clone --depth=1 https://github.com/vnt-dev/vnt.git
    - name: Build Firmware
      env:
        TNAME: WR1200JS
        KERNEL: 3.4
      run: |
        # 创建目录并设置安全权限
        sudo mkdir -p /opt/rt-n56u /opt/images
        sudo chmod 755 /opt/rt-n56u /opt/images
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        sudo echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        sudo cp -f configs/templates/$TNAME.config .config
        sudo sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        # 新增vnt配置项清理（保持原有注释风格）
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_VNT/d' .config #删除配置项VNT
        sudo sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        if [ $KERNEL = "4.4" ] ; then
        # ... [原有4.4内核配置保持不变] ...
        else
        sudo echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        sudo echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        sudo echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        sudo echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        sudo echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        sudo echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        sudo echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config #内网穿透FRPC
        sudo echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
        sudo echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        sudo echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
        sudo echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        sudo echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
        ######################################################################
        # 以下添加vnt配置（保持原有注释风格）
        ######################################################################
        sudo echo "CONFIG_FIRMWARE_INCLUDE_VNT=y" >> .config #VNT虚拟网络工具
        # ... [其他原有配置保持不变] ...
        fi
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        
        ######################################################################
        # 以下添加vnt编译步骤（新增部分）
        ######################################################################
        cd /opt/rt-n56u/trunk/user/vnt
        make clean
        make
        sudo cp vnt /opt/rt-n56u/trunk/user/romfs/bin/
        
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-WR1200JS
        path: /opt/images
