name: Build Padavan

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential flex bison gperf libcap-ng-dev \
          zlib1g-dev libssl-dev unzip curl cmake git python3-pip libncurses5-dev

    - name: Clone Source
      run: |
        git clone --depth=1 https://github.com/uwjtg/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        chmod +x dl_toolchain.sh
        ./dl_toolchain.sh

    - name: Build Firmware
      env:
        TNAME: WR1200JS  # 修改为您的设备型号
      run: |
        cd /opt/rt-n56u/trunk
        sudo make clean  # 清理旧编译缓存
        # 设置Storage分区为3MB
        sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x00080000/CONFIG_MTD_STORE_PART_SIZ=0x00300000/g' configs/templates/$TNAME.config
        # 启用FRPC插件
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> configs/templates/$TNAME.config
        
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mkdir -p /opt/images
        sudo cp -f images/*.trx /opt/images/ || exit 0

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padavan-Firmware
        path: /opt/images/
