- name: Build firmware
  env:
    DEVICE: ${{ inputs.device }}
  run: |
    set -ex  # 启用详细日志
    cd rt-n56u/trunk
    
    # 强制验证配置文件
    [ ! -f "configs/templates/$DEVICE.config" ] && echo "::error ::设备模板 $DEVICE.config 不存在" && exit 1
    
    # 修复权限问题
    sudo chmod -R 777 .
    
    # 核心编译命令
    fakeroot -- ./build_firmware_modify $DEVICE 0 2>&1 | tee build.log  # 
    
    # 产物收集（严格校验）
    mkdir -p ../output
    if ls images/*.trx >/dev/null 2>&1; then
      mv -v images/*.trx ../output/
    else
      echo "::error ::编译未生成固件文件"
      exit 1
    fi
    cp build.log ../output/

- name: Upload artifacts
  uses: actions/upload-artifact@v4
  if: always()
  with:
    name: build-artifacts
    path: |
      rt-n56u/output/*.trx
      rt-n56u/output/build.log  # 
