name: Build Padavan-MI-R4A
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
    - name: 克隆源码
      uses: actions/checkout@v4
      with:
        repository: uwjtg/rt-n56u
        submodules: recursive
        path: rt-n56u

    - name: 应用配置
      run: |
        cd rt-n56u/trunk
        cp configs/templates/MI-R4A.config .config
        
        # 修正后的sed命令
        sed -i 's/^$$CONFIG_FIRMWARE_INCLUDE_VNTCLI=$$.*/\1y/' .config
        sed -i 's/^$$CONFIG_FIRMWARE_INCLUDE_VNTS=$$.*/\1y/' .config
        sed -i 's/^$$CONFIG_FIRMWARE_WIFI2_DRIVER=$$.*/\13.0/' .config  # 驱动版本
        
    - name: 构建工具链
      run: |
        cd rt-n56u/toolchain-mipsel
        ./clean_sources
        ./build_toolchain_5.10

    - name: 编译固件
      run: |
        cd rt-n56u/trunk
        ../clear_tree
        ../build_firmware | tee build.log

    - name: 发布固件
      uses: actions/upload-artifact@v4
      with:
        name: MI-R4A-Firmware
        path: rt-n56u/trunk/images/*.trx
