name: Build Padavan-MI-R4A
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
    - name: 克隆源码
      uses: actions/checkout@v4
      with:
        repository: uwjtg/rt-n56u
        submodules: recursive
        path: rt-n56u

    - name: 应用配置
      run: |
        cd rt-n56u/trunk
        cp configs/templates/MI-R4A.config .config
        
        # 强制启用VNT插件
        sed -i 's/^$$CONFIG_FIRMWARE_INCLUDE_VNTCLI=$$.*/\1y/' .config
        sed -i 's/^$$CONFIG_FIRMWARE_INCLUDE_VNTS=$$.*/\1y/' .config
        
        # 硬件适配调整
        sed -i 's/CONFIG_MTD_STORE_PART_SIZ=.*/CONFIG_MTD_STORE_PART_SIZ=0x200000/' .config  # 2MB存储空间
        echo "CONFIG_FIRMWARE_WIFI2_DRIVER=3.0" >> .config  # MT7603稳定驱动

    - name: 构建工具链
      run: |
        cd rt-n56u/toolchain-mipsel
        ./clean_sources
        ./build_toolchain_5.10

    - name: 编译固件
      run: |
        cd rt-n56u/trunk
        ../clear_tree
        echo "开始编译，预计耗时30-50分钟..."
        ../build_firmware | tee build.log
        
        # 体积验证
        FIRMWARE_SIZE=$(du -b images/*.trx | cut -f1)
        if [ $FIRMWARE_SIZE -gt 15728640 ]; then  # 15MB限制
          echo "::error::固件体积超过15MB，当前大小：$(($FIRMWARE_SIZE/1024/1024))MB"
          exit 1
        fi

    - name: 发布固件
      uses: actions/upload-artifact@v4
      with:
        name: MI-R4A-VNT-Firmware
        path: |
          rt-n56u/trunk/images/*.trx
          rt-n56u/trunk/build.log
