name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        sudo chmod -R 777 /opt
        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sudo sh dl_toolchain.sh
        sudo mkdir -p /opt/images/

    - name: Setup VNT
      run: |
        # 下载VNT二进制文件<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">1</a><a target="_blank" href="https://gitee.com/xiueb_admin/actions-build-padavan-openwrt?skip_mobile=true" class="hitref" data-title="actions-build-padavan-openwrt: GitHub Action 学习实例 - Gitee" data-snippet='GitHub Action 学习实例- 自动编译padavan 和openWrt. ... Gitee 持续集成 · OpenAPI · 帮助文档 · 在线自助服务 · 更新日志 · 关于我们 · 加入我们 · 使用条款 · 意见建议.' data-url="https://gitee.com/xiueb_admin/actions-build-padavan-openwrt?skip_mobile=true">10</a>
        sudo mkdir -p /opt/rt-n56u/trunk/user/scripts
        wget https://github.com/vnt-dev/vnt/releases/latest/download/vnt-mipsel -O /opt/rt-n56u/trunk/user/scripts/vnt
        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/vnt
        
        # 创建自启动脚本<a target="_blank" href="https://okhk.net/build-padavan-firmware-for-rm2100" class="hitref" data-title="利用GitHub Action 自定义构建Padavan 路由固件 - HK&#39;s note" data-snippet='首先，在GitHub 上新建一个仓库，并下载Padavan 固件的源代码。然后，根据自己的需求修改配置文件和自定义脚本。接着，在GitHub Action 的配置文件中设置编译 ...' data-url="https://okhk.net/build-padavan-firmware-for-rm2100">3</a>
        echo -e '#!/bin/sh\n/opt/rt-n56u/trunk/user/scripts/vnt &' | sudo tee /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh
        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh

    - name: Build Firmware
      env:
        TNAME: WR1200JS
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        sudo cp -f configs/templates/$TNAME.config .config
        
        # 清理旧配置<a target="_blank" href="https://okhk.net/build-padavan-firmware-for-rm2100" class="hitref" data-title="利用GitHub Action 自定义构建Padavan 路由固件 - HK&#39;s note" data-snippet='首先，在GitHub 上新建一个仓库，并下载Padavan 固件的源代码。然后，根据自己的需求修改配置文件和自定义脚本。接着，在GitHub Action 的配置文件中设置编译 ...' data-url="https://okhk.net/build-padavan-firmware-for-rm2100">3</a><a target="_blank" href="https://gitee.com/xiueb_admin/actions-build-padavan-openwrt?skip_mobile=true" class="hitref" data-title="actions-build-padavan-openwrt: GitHub Action 学习实例 - Gitee" data-snippet='GitHub Action 学习实例- 自动编译padavan 和openWrt. ... Gitee 持续集成 · OpenAPI · 帮助文档 · 在线自助服务 · 更新日志 · 关于我们 · 加入我们 · 使用条款 · 意见建议.' data-url="https://gitee.com/xiueb_admin/actions-build-padavan-openwrt?skip_mobile=true">10</a>
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_VNT/d' .config
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        
        # 写入新配置
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" | sudo tee -a .config
        echo "CONFIG_FIRMWARE_INCLUDE_VNT=y" | sudo tee -a .config
        
        # 编译命令<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">1</a>
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: Padavan-${{ env.TNAME }}
        path: /opt/images/*.trx
