name: Build Padavan With VNT

on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TNAME: WR1200JS  # 修改为你的设备型号（需匹配configs/templates下的文件名）
      VNT_VERSION: v1.2.16  # VNT版本号<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a>

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip libtool-bin cmake gperf bison flex \
        gettext automake autopoint texinfo build-essential pkg-config zlib1g-dev

    - name: Setup toolchain
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sudo bash dl_toolchain.sh

    - name: Integrate VNT
      run: |
        # 下载VNT二进制（含重试机制）<a target="_blank" href="https://github.com/huazhuangnan/actions-build-padavan-openwrt" class="hitref" data-title="GitHub Action 学习实例- 自动编译padavan 和openWrt" data-snippet='前言 · openwrt 单独参数及功能说明 · padavan 单独参数及功能说明 · 下载编译完成固件 · 更新日志 · 本地编译 · github 编译方法 · 目录说明.' data-url="https://github.com/huazhuangnan/actions-build-padavan-openwrt">8</a>
        sudo mkdir -p /opt/rt-n56u/trunk/user/scripts
        for i in {1..3}; do
          wget https://github.com/vnt-dev/vnt/releases/download/${{ env.VNT_VERSION }}/vnt-mipsel \
            -O /opt/rt-n56u/trunk/user/scripts/vnt && break || sleep 15
        done
        
        # 备用下载源<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a>
        [ ! -f /opt/rt-n56u/trunk/user/scripts/vnt ] && \
          wget https://cdn.jsdelivr.net/gh/vnt-dev/vnt@${{ env.VNT_VERSION }}/bin/mipsel/vnt \
          -O /opt/rt-n56u/trunk/user/scripts/vnt
        
        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/vnt
        echo -e '#!/bin/sh\n/opt/etc/storage/vnt &' | sudo tee /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh
        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh

    - name: Build firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo cp configs/templates/${{ env.TNAME }}.config .config
        
        # 配置VNT集成<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a><a target="_blank" href="https://github.com/huazhuangnan/actions-build-padavan-openwrt" class="hitref" data-title="GitHub Action 学习实例- 自动编译padavan 和openWrt" data-snippet='前言 · openwrt 单独参数及功能说明 · padavan 单独参数及功能说明 · 下载编译完成固件 · 更新日志 · 本地编译 · github 编译方法 · 目录说明.' data-url="https://github.com/huazhuangnan/actions-build-padavan-openwrt">8</a>
        echo "CONFIG_FIRMWARE_INCLUDE_VNT=y" | sudo tee -a .config
        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config
        
        sudo ./clear_tree
        sudo ./build_firmware_modify ${{ env.TNAME }} 0
        sudo mv images/*.trx $GITHUB_WORKSPACE/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padavan-WR1200JS
        path: $GITHUB_WORKSPACE/*.trx
